# Generated by Django 5.2 on 2025-05-06 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_projectmanager_project_projectmanager'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='projectManager',
            new_name='projectmanager',
        ),
    ]
